// 自動生成的代碼。請勿編輯。
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image4":
            case "Temporary asset1":return img`
..........fffffffff...........
........ffcccccccccff.........
......ffccaaaaaaaaaccf........
.....f5fcaaafaaaaaaaf5f.......
....f555ffff9fffffff555f......
...f5545555f6f5555555545f.....
...f54ffff45f54ffffff444f.....
...f4fccccfffffccccccff45f....
...ffcaaaaaaaaaaaaaaaccf4f....
....fcaffffffffffffaaaccff....
....fafdccddddddccdfaaacf.....
....fafdddddddddddddfaacf.....
....fafdfdddddddfdddfaacf.....
....fafdfdddddddfdddfaacf.....
....faf3ddddddddd3ddfaacf.f...
.....ffffffffffffffffffcffcf..
.....f445555f555555544fcccf...
.....ff8996f9f6699998fffff....
...ff88699ff8ff99999688f......
...f8669ff4fff4fff999968f.....
....fffff44fcf44fffff668f.....
.....f66f45fcf54f9966fff......
....f699f55fcf55f99966f.......
...f699ff55fff55ff99996f......
...fffffff5f.f5fffffff96f.....
.......fffff.ff.fff...fff.....
........ff.......ff...........
..............................
..............................
..............................
`;
            case "image5":
            case "Temporary asset2":return img`
...........fffffffff..........
.........ffcccccccccff........
........fccaaaaaaaaaccff......
.......f5faaaaaaafaaacf5f.....
......f555fffffff9ffff555f....
.....f5455555555f6f5555455f...
.....f444ffffff45f54ffff45f...
....f54ffccccccfffffccccf4f...
....f4fccaaaaaaaaaaaaaaacff...
....ffccaaaffffffffffffacf....
.....fcaaafdccddddddccdfaf....
.....fcaafdddddddddddddfaf....
.....fcaafdddfdddddddfdfaf....
.....fcaafdddfdddddddfdfaf....
...f.fcaafdd3ddddddddd3faf....
..fcffcffffffffffffffffff.....
...fcccf445555555f555544f.....
....fffff8999966f9f6998ff.....
......f88699999ff8ff99688ff...
.....f869999fff4fff4ff9668f...
.....f866fffff44fcf44fffff....
......fff6699f45fcf54f66f.....
.......f66999f55fcf55f996f....
......f69999ff55fff55ff996f...
.....f69fffffff5f.f5fffffff...
.....fff...fff.ff.fffff.......
...........ff.......ff........
..............................
..............................
..............................
`;
            case "image9":
            case "myImage2":return img`
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
..............................
`;
            case "image11":
            case "myImage3":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
            case "image12":
            case "Temporary asset5":return img`
..........fffffffff...........
........ffb3333333bff.........
.......fbb333333333bbf........
......fb3333f333f3333bf.......
.....f333333fb3bf333333f......
....f3f333fb3fbf3bf333f3f.....
...fb3f33fffffffffff33f3bf....
...f33fbffdddddddddffbf33f....
...f3ffffdbbdddddbbdffff3f....
...f3f.fdddddddddddddf.f3f....
...f3f.fdddedddddedddf.f3f....
...f3f.fdddedddddedddf.f3f....
...f3f.ffdddddddddddff.f3f....
...f3f..ffdddddddddff..f3f....
...fbf....fffffffff....fbf....
...fbf...fbbf111fbbf...fbf....
...fbf..fbbff1f1ffbbf..fbf....
....f..fbffff1f1ffffbf..f.....
......ffbbbbf1f1fbbbbff.......
.....ffbbffbbfffbbffbbff......
.....fdff.fbbbfbbbf.ffdf......
.....fff..fbbbfbbbf..fff......
.........fbbbbffbbbf..........
........fbbbbbfffbbbf.........
.......fbbbbbbfdffbbbf........
......fbbbbbbffddffbbbf.......
.....fbbbbbbfffffffffbbf......
....ffffffffff.ffffffffff.....
...........ff...ff............
..............................
`;
            case "image13":
            case "Temporary asset6":return img`
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
........................................
`;
            case "image1":
            case "Temporary asset":return img`
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
..................................................
.....................3333.........................
........................33........................
.........................3........................
.......................333333.....................
.....................3333333333...................
....................333333333333..................
............333..3333333333433333.................
...........33333333333333344433333................
....3cc3333333333333333334444433333...............
.33333c3333333333333343242222242343...............
.....cc.....33333333333dd4ddd4ddd333..............
.............3333333333ddddddddddd33..............
.............3333333333d1c1111cd1d33..............
..............333..333d11b1111b11d333.............
...................333d1111111111d333.............
....................33d1111111111d333.............
.....................3d11111111ddd333.............
......................d111d1111ddd333.............
......................d32442233eed3d..............
.......................1111ee33eed3dd.............
......................d1111ee33eedddd.............
......................d111133eeeedddd.............
.....................ddddee33ee33eddd.............
.....................ddddeedd33eeeeed.............
....................ddddd33eeeeeeeee.d............
......................11d33eeeeeee11.dd...........
.......................111333311111d..ddddd.......
.......................3d11333111.ddd.ddddd.......
........................1113111111d.dd....d.......
......................bb111111111d..dd...dd.......
..................bbbbbb111bbb111...d....dd.......
................bbbbbbbb111bbb111...d.....d.......
..............bbbbbbbbbb111bbb111.bbd.....d.......
.................bbbbbbbbbbbbb111bbbdd....d.......
..................bbbbbbbbbbbb111bbbbdb.ddd.......
...........................bbbbbbbbdddbbbbbb......
..............................bbbbbbb.bbbbbb......
................................bbbbbbb...........
..................................................
..................................................
..................................................
..................................................
`;
            case "image2":
            case "Temporary asset0":return img`
..........fffffffff...........
........ffcccccccccff.........
.......fccaaaaaaaaaccf........
......f5faaaaafaaaaaf5f.......
.....f555fffff9fffff555f......
....f54555555f6f55555545f.....
....f444ffff55f55ffff444f.....
...f54ffccccfffffccccff45f....
...f4fccaaaaaaaaaaaaaccf4f....
...ffccaaafffffffffaaaccff....
....fcaaafccdddddccfaaacf.....
....fcaffdddddddddddffacf.....
....fcafddfdddddddfddfacf.....
....fcafddfdddddddfddfacf.....
..f.fcaf33ddddddddd33facf.f...
.fcffcfffffffffffffffffcffcf..
..fcccf4455555f5555544fcccf...
...fffff89996f9f69998fffff....
.....f886999ff8ff999688f......
....f8699fff4fff4fff9968f.....
....f866fff45fcf54fff668f.....
.....fff69f45fcf54f96fff......
......f669f55fcf55f966f.......
.....f699ff55fff55ff996f......
....f699ffff4f.f4ffff996f.....
....ffffffffff.ffffffffff.....
........fff.......fff.........
.........ff.......ff..........
..............................
..............................
`;
            case "image6":
            case "myImage0":return img`
. . . . . . . f f f f f . . . . 
. . . . . f f 6 6 6 6 6 f f . . 
. . . . f 6 6 6 6 6 6 6 6 6 f . 
. . . f 6 6 6 6 6 6 6 6 6 6 6 f 
. . . f 6 8 8 6 9 6 6 6 6 9 6 f 
. . . f 6 8 8 6 9 6 6 6 6 9 6 f 
. . . f 6 6 6 6 6 6 6 6 6 6 6 f 
. . . f 6 6 6 6 6 6 6 f 6 6 6 f 
. . . f 6 6 6 6 6 6 6 6 6 6 6 f 
. . . f 6 6 6 6 6 6 6 6 6 6 6 f 
. . . f 6 6 6 8 8 8 6 6 6 6 6 f 
. . f 8 6 6 6 8 8 8 8 6 6 6 8 f 
. f 8 8 8 8 6 6 8 8 8 8 6 6 8 f 
f f f f f f f f f f f f f f f f 
. . . . . . . . . . . . . . . . 
`;
            case "image8":
            case "myImage1":return img`
. . . f f f f f f f f f f . . . 
. . f 4 4 4 4 4 4 4 4 4 4 f . . 
. f 4 5 5 5 5 5 5 5 5 5 5 f . . 
. f 5 5 5 5 f f f f f f f f . . 
. f 5 5 5 5 f 6 9 9 6 6 6 f f . 
. f 5 5 5 5 f 9 6 6 9 9 9 f 4 f 
. f 5 5 5 5 4 f f f f f f f 5 f 
f f 4 4 5 5 5 5 5 5 5 4 4 f 5 f 
f 2 f 4 5 5 5 5 5 5 5 5 4 f f . 
f 2 2 f f f f f f f f f f f . . 
. f f f 2 2 2 2 2 2 2 2 f f f f 
f 4 4 4 f f f f f f f f 4 4 4 f 
f 5 5 5 f e e e e e e f 5 5 5 f 
f 5 5 f f f f f f f f f f 5 5 f 
f f f . . . . . . . . . . f f f 
. . . . . . . . . . . . . . . . 
`;
            case "image3":
            case "myImage":return img`
.............bf.f.c..f..c.f.fb.............
.............bfcfcfcfffcfcfcfb.............
..........cfcbfcbfcfccbfcfccfbcfb..........
........cfffccffccffccbffccffccfffb........
.........ccfffcffbbfcbbfcbffcfffcc.........
.....cf..fbcfcbcfcbbfbfbcbfcccfcbf..fc.....
.....ffcbcfcbfffccfffffffbcfffccfbccff.....
....b.ffbbcfccbbffcaacaccffccbbfbbcff.b....
.....cbfffcbfcbffcaaaaaaacffbcfccfffcb.....
.....ffcccfffcffcaaaaaaaaacffcfffcccff.....
.......fffcbbfacaaaaaaaaaaacafbbcfff.......
.........fbbfccaaaaaaaaaaaaaccfbbf.........
..........ffffbbffffaaaffffbbffff..........
............fabff2ffaaaff2ffbaf............
............fcaffffcaaacffffacf............
............fcaaaaaaaaaaaaaaacf............
............fbaaaaaaaaaaaaaaabf............
............fbbbaaaafcfaaaabbbf............
............fffbccfcfffcfccbfff............
.............fffbf1111111fbfff.............
........ffffffbaf1f1f1f1f1fabffffff........
.........f555ffbfffffffffffbff555f.........
.........fff5fffbf1f1f1f1fbfff5fff.........
...........f5ffffbf11111fbffff5f...........
...........ff5fffffacaaafffff5ff...........
............ff5fffffffffffff5ff............
.............ff5fffffffffff5ff.............
..............f5554fffff4555f..............
.............fffff44fff44fffff.............
.............ffffff4fff4ffffff.............
............fffffff4faf4fffffff............
............ffffff5ffaff5ffffff............
...........fffffff5fbabf5fffffff...........
...........fffffff5fbabf5fffffff...........
..........ffffffff5fbabf5ffffffff..........
..........ffffffff5faaaf5ffffffff..........
.........ffffffff55fbabf55ffffffff.........
.........ffffffff5ffbabff5ffffffff.........
........fffffffff5fbbabbf5fffffffff........
........fffffffff5faaaaaf5fffffffff........
.......ffffffffff5fbbabbf5ffffffffff.......
.......ffffffffff5fbbabbf5ffffffffff.......
......fffffffffff5fbbabbf5fffffffffff......
......fffffffffff5faaaaaf5fffffffffff......
.....ffffffffffff5fbbabbf5ffffffffffff.....
.....ffffffffffff5fbbabbf5ffffffffffff.....
....fffffffffff555fbbabbf555fffffffffff....
....fffffffffff5fffaaaaafff5fffffffffff....
...fffffffffff55faaaaaaaaaf55fffffffffff...
..ff5fff55555555faaaaaaaaaf55555555fff5ff..
.fff55555ffffffffccfffffccffffffff55555fff.
fffffffffffffffffcff...ffcfffffffffffffffff
................fff.....fff................
.................ff.....ff.................
`;
            case "image7":
            case "Temporary asset3":return img`
.........fffffffff........
.......ff455555554ff......
......f5555555555555f.....
.....f455555555555554f....
....f455555f454f555554f...
....f555555f454f555555f...
...ff5555f45f4f54f5555ff..
...f555fffffffffffff555f..
...f555fdddddddddddf555f..
...f55ffdeedddddeedff55f..
...f54fdddddddddddddf45f..
...f54fddd4ddddd4dddf45f..
...f54fddd5ddddd5dddf45f..
...f54fdddddddddddddf45f..
...f44fffffffffffffff44f..
...ff4f1111111111111f4ff..
....f4fffffffffffffff4f...
.....ffbbbf11111fbbbff....
....ffbbbbbfffffbbbbbff...
...fbbbbbbffbfbffbbbbbbf..
22.fbbbffffbbfbbffffbbbf..
22fdfffbbbbbbfbbbbbbfffdf.
.fddf.fbbbbbfffbbbbbf.fddf
.fff.fbbbbbffcffbbbbbf.fff
....fbbbbbffcccffbbbbbf...
...ffffffffcccccffffffff..
.......fffffffffffff......
........ff.......ff.......
`;
            case "image10":
            case "Temporary asset4":return img`
.........f.f.........
..........f..........
......fffffffff......
.....ff1111111ff.....
...ff11111111111ff...
...f1111111111111f...
..f111111111111111f..
.ff111f111f111f111ff.
.f111f111f1f111f111f.
f11ffdf1fdddf1fdff11f
.f1fdddfdddddfdddf1f.
..ffdd111ddd111ddff..
...fddd2ddddd2dddf...
...fdddfdddddfdddf...
....fdddddddddddf....
...fffffffffffffff...
...fcccccccccccccf...
..fffffffffffffffff..
..faaafcccccccfaaaf..
.faaaaffffcffffaaaaf.
.faaaaaaafffaaaaaaaf.
faaffaaaaaaaaaaaffaaf
faf.faaafffffaaaf.faf
ff..fffffbbbfffff..ff
....ffbbbbbbbbbff....
.....fbbbfffbbbf.....
.....ffbbf.fbbff.....
......ffff.ffff......
......fff...fff......
.......ff...ff.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// 自動生成的代碼。請勿編輯。
